#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080

# Start apache if present
if [ -d "$OPENSHIFT_HOMEDIR/app-root/runtime/srv/httpd" ]; then
    $OPENSHIFT_HOMEDIR/app-root/runtime/srv/httpd/bin/apachectl start > $OPENSHIFT_DIY_LOG_DIR/server.log 2>&1 &
fi


/* Environment variables exposed by MySQL database cartridge */
define('DB_HOST', getenv('OPENSHIFT_MYSQL_DB_HOST')); 
define('DB_PORT', getenv('OPENSHIFT_MYSQL_DB_PORT')); 
define('DB_USER', getenv('OPENSHIFT_MYSQL_DB_USERNAME')); 
define('DB_PASS', getenv('OPENSHIFT_MYSQL_DB_PASSWORD')); 
define('DB_NAME', getenv('OPENSHIFT_APP_NAME')); 
define('DB_SOCKET', getenv('OPENSHIFT_MYSQL_DB_SOCKET')); // $OPENSHIFT_MYSQL_DIR/socket/mysql.sock
define('DB_STRING', getenv('OPENSHIFT_MYSQL_DB_URL')); // mysql://<user>:<pass>@127.0.250.1:3306/
